### ISSUE TITLE
mysql connect版本太高了

### ISSUE THREAD

**Issue by spiritman1990** [lyy289065406/jira-docker#2]
折腾了一下，7.x版本连接mysql 5.7 用8.0的mysql-connecter jar包不行

**Comment by zhuliangyu** [comment]
![image](https://user-images.githubusercontent.com/11518998/218400753-c715ed29-ab21-4986-b75d-bfa632e70603.png)

Simply use mysql-connector-java-5.1.47 instead of mysql-connector-java-8.0.15, then the issue is gone.

**Comment by elvin-zheng** [comment]
jira 的版本有限制么？
